### ISSUE TITLE
Java Object tab not appearing, JARs keep loading

### ISSUE THREAD

**Issue by tratond01** [omercnet/BurpJDSer-ng#38]
Hi, thanks a lot for the project. 
But the extension doesn't currently seem to be working:
After successful installation, no "Java Object" tab appeared.
And when I select the serialized object and right-click > Extensions > Reload JARs, the extension only keeps reloading the JARs without deserialization or any other option to send to other tabs. 

Is there a possibility to publish a new release? 
Thank you very much.

**Comment by mladjen** [comment]
Hi @tratond01, i installed this version of burp and it worked! https://portswigger.net/burp/releases/professional-community-2020-4-1

**Comment by omercnet** [comment]
hi @tratond01 @mladjen try the new release, updated it to the latest API - would appreciate any feedback
